# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: utf8
  database: Bnmmq_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: Bnmmq_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: Bnmmq_production
  pool: 5
  username: postgres
  password: postgres
